apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zdtjgctum-nodejs 
  janus-idp.io/tekton: zdtjgctum-nodejs
  backstage.io/kubernetes-id: zdtjgctum-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zdtjgctum-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml